### ISSUE TITLE
how to start? any guide ?

### ISSUE THREAD

**Issue by andyyuan78** [ramarlina/DenoisingAutoEncoder#1]
ubgpu@ubgpu:~/github/DenoisingAutoEncoder$ python demo.py

Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from SDA_layers import StackedDA
  File "/home/ubgpu/github/DenoisingAutoEncoder/SDA_layers.py", line 2, in <module>
    from dA import dA
ImportError: No module named dA
ubgpu@ubgpu:~/github/DenoisingAutoEncoder$

**Comment by ramarlina** [comment]
Hi, andyyan78, thank you for reporting this issue. I've updated the demo to fix this issue.
